name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - Examples/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - Examples/**

jobs:
  run-macos:
    name: ${{ matrix.subcommand }} with Xcode ${{ matrix.xcode }} on macOS
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ["14.3.1"]
        subcommand: ["Build", "Test"]
    steps:
    - uses: actions/checkout@v3
    - name: ${{ matrix.subcommand }}
      run: |
        xcodebuild -version
        swift --version
        swift package --version
        subcommand=`echo ${{ matrix.subcommand }} | tr '[:upper:]' '[:lower:]'`
        swift $subcommand -v
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app

  run-ubuntu:
    name: Build and Test with Swift ${{ matrix.swift }} on Ubuntu
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    strategy:
      matrix:
        swift: ["5.8.1"]
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        swift --version
        swift package --version
        swift test -v

